# ================= 网站基础信息 =================
baseURL = "https://zlong.work/" # 部署成功后，请替换为您的实际网址
languageCode = "zh-cn"              # 网站语言
title = "跳龙同学的技术博客"               # 网站标题
theme = "PaperMod"                  # 使用的主题

# ================= 主题核心配置 =================
[params]
  env = "production"                # 生产环境，会启用部分优化功能
  description = "记录技术与思考"     # 网站描述，用于 SEO
  author = "zlong"                # 作者名称
  
  # 界面与交互优化
  defaultTheme = "auto"             # 自动跟随系统切换深色/浅色模式
  ShowReadingTime = true            # 显示文章预估阅读时间
  ShowCodeCopyButtons = true        # 代码块显示复制按钮（技术博客必备）
  ShowBreadCrumbs = true            # 显示面包屑导航，方便跳转
  ShowShareButtons = true           # 显示文章分享按钮
  disableThemeToggle = false        # 保留右上角的主题切换按钮

# ================= 首页个性化配置 =================
[params.homeInfoParams]
  Title = " 欢迎来到我的博客"
  Content = "在这里，我记录日常的技术探索与生活感悟。"

# ================= 顶部导航栏菜单 =================
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 5
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 15
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 20

timeZone = 'Asia/Shanghai'
# ================= 开启站内搜索功能 =================
[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON 输出是搜索功能的基础