name: Hugo Deploy

on:
  push:
    branches:
      - main  # 当向 main 分支推送代码时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # 如果您的主题是通过 submodule 引入的，必须开启此项
          token: ${{ secrets.GITHUB_TOKEN }} # 这行代码显式使用 GITHUB_TOKEN，确保有足够权限

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}